---
title: "dagging it"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
library(dplyr)
library(ggplot2)
```


```{r}
data("WaffleDivorce")
d <- WaffleDivorce

d <- d %>% 
  mutate(D = standardize(Divorce), 
         M = standardize(Marriage), 
         A = standardize(MedianAgeMarriage))


```



```{r m51}
m5_1 <- quap(
  alist(
    D ~ dnorm(mu, sigma),
    mu <- a + bA * A,
    a ~ dnorm(0, .2),
    bA ~ dnorm(0, .5),
    sigma ~ dexp(1)
  ), data = d
)


set.seed(10)
prior <- extract.prior(m5_1)
mu <- link(m5_1, post = prior, data = list(A = c(-2, 2)))



```

```{r}
library(dagitty)
DMA_dag1 <- dagitty("dag{ A -> D; A -> M; M -> D}")
drawdag(DMA_dag1)
impliedConditionalIndependencies(DMA_dag1)

```

```{r}

DMA_dag2 <- dagitty("dag{ M <- A -> D}")
drawdag(DMA_dag2)
impliedConditionalIndependencies(DMA_dag2)
```


```{r}
data(WaffleDivorce)
d <- list()
d$A <- standardize( WaffleDivorce$MedianAgeMarriage )
d$D <- standardize( WaffleDivorce$Divorce )
d$M <- standardize( WaffleDivorce$Marriage )

m5.3_A <- quap(
    alist(
      ## A -> D <- M
        D ~ dnorm( mu , sigma ) ,
        mu <- a + bM*M + bA*A ,
        a ~ dnorm( 0 , 0.2 ) ,
        bM ~ dnorm( 0 , 0.5 ) ,
        bA ~ dnorm( 0 , 0.5 ) ,
        sigma ~ dexp( 1 ),
      ## A -> M
        M ~ dnorm( mu_M , sigma_M ),
        mu_M <- aM + bAM*A,
        aM ~ dnorm( 0 , 0.2 ),
        bAM ~ dnorm( 0 , 0.5 ),
        sigma_M ~ dexp( 1 )
    ) , data = d )


```

```{r}
precis(m5.3_A)
```

```{r}
## R code 5.20
A_seq <- seq( from=-2 , to=2 , length.out=5 )

## R code 5.21
# prep data
sim_dat <- data.frame( A=A_seq )

# simulate M and then D, using A_seq
s <- sim( m5.3_A , data=sim_dat , vars=c("M","D") )
```


```{r}
## R code 5.22
plot( sim_dat$A , colMeans(s$D) , ylim=c(-2,2) , type="l" ,
    xlab="manipulated A" , ylab="counterfactual D"  )
shade( apply(s$D,2,PI) , sim_dat$A )
mtext( "Total counterfactual effect of A on D" )
```

```{r}

df <- tibble(
  A = sim_dat$A,
  D = colMeans(s$D),
  M = colMeans(s$M)
)

lm(M ~ A, data = df)
lm(D ~ A, data = df)



```

```{r}
## R code 5.23
# new data frame, standardized to mean 26.1 and std dev 1.24
sim2_dat <- data.frame( A=(c(20,30)-26.1)/1.24 )
s2 <- sim( m5.3_A , data=sim2_dat , vars=c("M","D") )
mean( s2$D[,2] - s2$D[,1] )

## R code 5.24
sim_dat <- data.frame( M=seq(from=-2,to=2,length.out=30) , A=0 )
s <- sim( m5.3_A , data=sim_dat , vars="D" )

plot( sim_dat$M , colMeans(s) , ylim=c(-2,2) , type="l" ,
    xlab="manipulated M" , ylab="counterfactual D"  )
shade( apply(s,2,PI) , sim_dat$M )
mtext( "Total counterfactual effect of M on D" )
```


```{r}

# do the models have to be fit at the same time?

## R code 5.25
A_seq <- seq( from=-2 , to=2 , length.out=30 )

## R code 5.26
post <- extract.samples( m5.3_A )

dim(post)

M_sim <- with( post , sapply(seq_along(A_seq) ,
    function(i) rnorm( 1e3 , aM + bAM*A_seq[i] , sigma_M ) ) ) # this only looks at the first 1e3 posterior samples

dim(M_sim)

## R code 5.27
D_sim <- with( post , sapply(seq_along(A_seq) ,
    function(i) rnorm( 1e3 , a + bA*A_seq[i] + bM*M_sim[,i] , sigma ) ) )
```

```{r}
dag5.7 <- dagitty( "dag{
    K [outcome]
    M [exposure]
    N [unobserved]
    M -> K <- N
    M -> N }" )
coordinates(dag5.7) <- list( x=c(M=0,K=1,N=2) , y=c(M=0.5,K=1,N=0.5) )

outcomes(dag5.7) <- "K"
drawdag(dag5.7)

MElist <- equivalentDAGs(dag5.7)
drawdag(MElist)
```

